
data:
  dataset: 'IACTA'
  csv_path: 'F:/data/Medzoo_code_use_data/debug/aneurysm_seg_debug.csv' # all data
  brain_file: 'F:/data/Medzoo_code_use_data/debug/brain_coords.txt'
  data_dir: 'F:/data/Medzoo_code_use_data/debug'
  split_test: 1
  split_train: 5
  split_fold_valid : 1
  split_fold_train: 4
  fold_num: 5
  fold_1:
    random_seed: 13
    save_path: 'F:/data/Medzoo_code_use_data/debug/fold/fold_1'
  fold_2:
    random_seed: 31
    save_path: 'F:/data/Medzoo_code_use_data/debug/fold/fold_2'
  fold_3:
    random_seed: 7
    save_path: 'F:/data/Medzoo_code_use_data/debug/fold/fold_3'
  fold_4:
    random_seed: 11
    save_path: 'F:/data/Medzoo_code_use_data/debug/fold/fold_4'
  fold_5:
    random_seed: 71
    save_path: 'F:/data/Medzoo_code_use_data/debug/fold/fold_5'

  hu_values: [[0, 100], [100, 200], [200, 800]]  # HU value intervals  for input images. Length should be same as in_channels
  train_pos_neg_ratio: [1, 1]  # ratio for positive and negative patches during training
  eval_pos_neg_ratio: [1, 1]  # ratio for positive and negative patches during eval
  patch_size: [96, 96, 96]  # depth, width, height
  overlap_step: [48, 48, 48]  # only in sliding window data generation method


train:
  train_save_dir: 'F:/saved_models/debug'
  model: 'UNET3D' #'VNET', 'VNET2', 'UNET3D', 'DENSENET1', 'DENSENET2', 'DENSENET3', 'HYPERDENSENET'
  nEpochs: 8
  classes: 2
  inChannels: 3
  inModalities: 1
  terminal_show_freq: 50
  lr: 0.01
  opt: 'sgd' #('sgd', 'adam', 'rmsprop')
  batchSz: 4

inference:
  just_brain: True
  brain_flag: '_Brain_'  #save name
  pretrained: 'F:\saved_models\debug\IACTA_UNET3D\1\fold_1\fold_1_BEST.pth'
  kernel_size: 7 # kernel size in morph close
  area_threshold: 30 #target whose area is no more than this threshold will be dropped
  thin_threshold: 1 #target who has no more than this number of slices along any axis will be dropped

# note that eval phase metrics in training is patch-wise with overlap among patches, not case-wise
eval:
  # supported metrics: ap, auc, precision, recall, sensitivity, specificity, dsc, hd95, tp, fp, fn, tn.
  # metrics are per voxel by default. add prefix per_target_ to compute per target metrics
  # the first is the main eval metric
  metrics: [ap, auc, precision, recall, dsc, hd95, per_target_precision, per_target_recall]
  # curves will be logged to tensorboard after each epoch
  # supported curves: pr (precision-recall curve), roc (ROC curve)
  # metrics are per voxel by default. add prefix per_target_ to compute per target metrics
  curves: [pr, roc]
  num_thresholds: 100  # for computing AUC and AP
  thresholds_type: uline  # logspace, linspace, logspace_pro or uline. see in get_evaluation_metric()
  eval_score_higher_is_better: True  # just for the first metric
  probability_threshold: 0.5  # for precision, recall...
  skip_eval_metric_in_training: False  # if true, skip eval metrics on training set.
